baseURL = 'https://ic-ufrj.github.io/python-ufrj'
languageCode = 'pt_BR'
title = 'Python UFRJ'


# Para instalar o tema, eu deszipei dentro da pasta themes/
# As alternativas seriam usar git submodule, ou Go modules.
# Git submodules são uma fonte infinita de dor e sofrimento; evite.
# Go modules precisariam de instalar o runtime Go na máquina.
theme = 'relearn-5.23.2'

[markup.highlight]
    # Cor do syntax highlighting color
    # Escolha uma compatível com o themeVariant do Relearn:
    # ambos temas claros ou ambos temas escuros
    style =  'abap'

[markup.goldmark.renderer]
    # Permite incluir tags HTML como <sup></sup>
    # Também é necessário para os plugins mermaid e mathjax
    # (Tome cuidado para não incluir HTML malvado sem querer)
    unsafe = true

[params]
    # Configuração do tema (Relearn)
    # https://mcshelby.github.io/hugo-theme-relearn/basics/configuration/index.html

    # Estes parâmetros afetam tags <meta>
    author.name = 'Instituto de Computação'
    description = 'Material do curso Computação I em Python'

    # Estes parâmetros mexem em coisas visíveis
    themeVariant = 'zen-light'
    disableSearch = true
    ordersectionsby = 'linktitle'
    alwaysopen = true
    highlightWrap = false # pois Python depende de identação
    disableInlineCopyToClipBoard = true
    disableHoverBlockCopyToClipBoard = false
    disableLandingPageButton = true
        #landingPageName = "<i class='fas fa-home'></i> Início"
